name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Copy .env file
      run: cp /Users/dmitrydisson/Downloads/foodgram-project-master/infra/.env .env
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Build the Docker image
      run: docker-compose up -d --build

    - name: Wait for DB
      run: |
        until docker-compose exec db pg_isready ; do
          sleep 1;
        done

    - name: Run tests
      run: docker-compose exec backend pytest

    - name: Run migrations
      run: docker-compose exec backend python manage.py migrate